export function getCountryFlag(countryName: string): string {
  if (!countryName) return '';
  
  const normalized = countryName.toLowerCase().trim();
  
  const flags: Record<string, string> = {
    'kuba': '🇨🇺',
    'cuba': '🇨🇺',
    'jamajka': '🇯🇲',
    'jamaica': '🇯🇲',
    'barbados': '🇧🇧',
    'dominikánska republika': '🇩🇴',
    'dominikanska republika': '🇩🇴',
    'dominican republic': '🇩🇴',
    'venezuela': '🇻🇪',
    'guyana': '🇬🇾',
    'martinik': '🇲🇶',
    'martinique': '🇲🇶',
    'guatemala': '🇬🇹',
    'nikaragua': '🇳🇮',
    'nicaragua': '🇳🇮',
    'panama': '🇵🇦',
    'panamá': '🇵🇦',
    'kolumbia': '🇨🇴',
    'colombia': '🇨🇴',
    'peru': '🇵🇪',
    'brazília': '🇧🇷',
    'brazilia': '🇧🇷',
    'brazil': '🇧🇷',
    'portoriko': '🇵🇷',
    'puerto rico': '🇵🇷',
    'haiti': '🇭🇹',
    'trinidad a tobago': '🇹🇹',
    'trinidad and tobago': '🇹🇹',
    'trinidad': '🇹🇹',
    'svätá lucia': '🇱🇨',
    'st. lucia': '🇱🇨',
    'saint lucia': '🇱🇨',
    'maurícius': '🇲🇺',
    'mauritius': '🇲🇺',
    'filipíny': '🇵🇭',
    'philippines': '🇵🇭',
    'usa': '🇺🇸',
    'spojené štáty': '🇺🇸',
    'mexiko': '🇲🇽',
    'mexico': '🇲🇽',
    'španielsko': '🇪🇸',
    'spain': '🇪🇸',
    'francúzsko': '🇫🇷',
    'france': '🇫🇷',
    'uk': '🇬🇧',
    'veľká británia': '🇬🇧',
    'anglicko': '🇬🇧',
    'slovensko': '🇸🇰',
    'slovakia': '🇸🇰',
    'česko': '🇨🇿',
    'czech republic': '🇨🇿',
    'czechia': '🇨🇿',
    'rakúsko': '🇦🇹',
    'austria': '🇦🇹',
    'nemecko': '🇩🇪',
    'germany': '🇩🇪',
    'taliansko': '🇮🇹',
    'italy': '🇮🇹',
    'austrália': '🇦🇺',
    'australia': '🇦🇺',
    'japonsko': '🇯🇵',
    'japan': '🇯🇵',
    'india': '🇮🇳',
    'thajsko': '🇹🇭',
    'thailand': '🇹🇭',
    'fidži': '🇫🇯',
    'fiji': '🇫🇯',
    'seychely': '🇸🇨',
    'seychelles': '🇸🇨',
    'madagaskar': '🇲🇬',
    'madagascar': '🇲🇬',
    'belize': '🇧🇿',
    'kostarika': '🇨🇷',
    'costa rica': '🇨🇷',
    'honduras': '🇭🇳',
    'salvádor': '🇸🇻',
    'el salvador': '🇸🇻',
    'ekvádor': '🇪🇨',
    'ecuador': '🇪🇨',
    'bolívia': '🇧🇴',
    'bolivia': '🇧🇴',
    'chile': '🇨🇱',
    'argentína': '🇦🇷',
    'argentina': '🇦🇷',
    'uruguaj': '🇺🇾',
    'uruguay': '🇺🇾',
    'paraguaj': '🇵🇾',
    'paraguay': '🇵🇾',
    'surinam': '🇸🇷',
    'suriname': '🇸🇷',
    'francúzska guayana': '🇬🇫',
    'french guiana': '🇬🇫',
    'bahamy': '🇧🇸',
    'bahamas': '🇧🇸',
    'bermudy': '🇧🇲',
    'bermuda': '🇧🇲',
    'kajmanské ostrovy': '🇰🇾',
    'cayman islands': '🇰🇾',
    'panenské ostrovy': '🇻🇬',
    'virgin islands': '🇻🇬',
    'antigua a barbuda': '🇦🇬',
    'antigua and barbuda': '🇦🇬',
    'svätý krištof a nevis': '🇰🇳',
    'st. kitts and nevis': '🇰🇳',
    'svätý vincent a grenadíny': '🇻🇨',
    'st. vincent and the grenadines': '🇻🇨',
    'grenada': '🇬🇩',
    'curacao': '🇨🇼',
    'curaçao': '🇨🇼',
    'aruba': '🇦🇼',
    'bonaire': '🇧🇶',
    'réunion': '🇷🇪',
    'reunion': '🇷🇪',
    'tahiti': '🇵🇫',
    'francúzska polynézia': '🇵🇫',
    'french polynesia': '🇵🇫',
    'južná afrika': '🇿🇦',
    'south africa': '🇿🇦',
    'kapverdy': '🇨🇻',
    'cape verde': '🇨🇻',
  };

  return flags[normalized] || '🌍';
}
